server:
  port: 8080

spring:
  application:
    name: springboot-single
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot_single?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: root
    #表明不使用默认的Hikari，而使用druid
    type: com.alibaba.druid.pool.DruidDataSource
    #druid配置
    druid:
      initial-size: 5 #初始化大小
      min-idle: 5 #最小
      max-active: 20  #最大
      max-wait: 60000 #获取连接等待超时的时间
      time-between-eviction-runs-millis: 60000 #配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒 60S
      min-evictable-idle-time-millis: 300000  # 配置一个连接在池中最小生存的时间，单位是毫秒300S
      #测试连接
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      # 配置监控统计拦截的filters
      filters: statc
      #asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
      async-init: true

#pagehelper:
#  #分页插件会自动检测当前的数据库链接，自动选择合适的分页方式。你也可以配置helperDialect属性来指定分页插件使用哪种方言
#  helper-dialect: mysql
#  #分页合理化参数，默认值为false。当该参数设置为 true 时，pageNum<=0 时会查询第一页， pageNum>pages（超过总数时），会查询最后一页。默认false 时，直接根据参数进行查询。
#  reasonable: false
#  #默认值false，分页插件会从查询方法的参数值中，自动根据params 配置的字段中取值，查找到合适的值时就会自动分页。
#  support-methods-arguments: true
#  #用于从对象中根据属性名取值，可以配置 pageNum,pageSize,count,pageSizeZero,reasonable，不配置映射的用默认值
#  #默认值为pageNum=pageNum;pageSize=pageSize;count=countSql;reasonable=reasonable;pageSizeZero=pageSizeZero
#  params: count=countSql

logging:
  level:
    com.minwujun.springbootdemo.mapper: debug

